version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.utils.tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - redis
      - celery
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
